### ISSUE TITLE
Failed to load pdf file 

### ISSUE THREAD

**Issue by fabulousmichael** [saadq/resumake.io#123]
Tried making a new CV after putting in details and information and I then click on MAKE, the page comes with an error message saying (Failed to load pdf file).

**Comment by akashcoc** [comment]
@fabulousmichael template #6?

**Comment by jimmyhuang** [comment]
I had an issue where I copied over bullet points (with whitespacing) and I received the same error. I would check your inputs again and make sure everything is plain text.

**Comment by holako1992** [comment]
> Tried making a new CV after putting in details and information and I then click on MAKE, the page comes with an error message saying (Failed to load pdf file).

Need to install latex first in your local machine to be able to compile:
https://www.latex-project.org/get/

**Comment by omerfraz** [comment]
I am having the same issue. I have tried MiKTeX but still same.

**Comment by omerfraz** [comment]
I did two things and problem was fixed on windows 10 (I cannot confirm which one of the two fixed the issue in my case).
1. Downloaded TexLive and installed it from the link
http://www.tug.org/texlive/acquire-netinstall.html

2. in webpack.dev.config.js edited proxy target https to http

    proxy: {
      '/api/**': {
		  target: 'http://localhost:3001',
		  //pathRewrite: { '^/api': '' },
			secure: false,
			changeOrigin: true	  
        //target: 'http://localhost:3001',
        //secure: false,

      }
    }

**Comment by saadq** [comment]
@omerfraz Could you share the error message from the terminal where you are running the Resumake server?

**Comment by omerfraz** [comment]
[HPM] Error occurred while trying to proxy request /api/generate/resume from localhost:3000 to [::1]:3001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by omerfraz** [comment]
And some tests!

 FAIL  src\tests\api.js (19.65s)
  ● Console

    console.error node_modules\koa\lib\application.js:194

    console.error node_modules\koa\lib\application.js:195
        Error: Error while running latexindent.
            at ChildProcess.<anonymous> (G:\resumake.io-master\app\server\node_modules\pretty-latex\index.js:62:22)
            at ChildProcess.emit (events.js:203:13)
            at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
    console.error node_modules\koa\lib\application.js:196


  ● POST /api/generate/resume should generate a PDF

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      at node_modules/jest-jasmine2/build/queue_runner.js:72:21

  ● POST /api/generate/source should generate a zip of the LaTeX source code

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      at node_modules/jest-jasmine2/build/queue_runner.js:72:21

Test Suites: 1 failed, 3 passed, 4 total
Tests:       2 failed, 8 passed, 10 total
Snapshots:   0 total
Time:        20.223s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! resumake.io@0.2.0 test:server: `cd app/server && npm test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the resumake.io@0.2.0 test:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\omerf\AppData\Roaming\npm-cache\_logs\2020-05-17T23_59_46_454Z-debug.log
npm ERR! Test failed.  See above for more details.

G:\resumake.io-master>
G:\resumake.io-master>

**Comment by omerfraz** [comment]
And contents of the log

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test:server'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.6.0
4 verbose run-script [ 'pretest:server', 'test:server', 'posttest:server' ]
5 info lifecycle resumake.io@0.2.0~pretest:server: resumake.io@0.2.0
6 info lifecycle resumake.io@0.2.0~test:server: resumake.io@0.2.0
7 verbose lifecycle resumake.io@0.2.0~test:server: unsafe-perm in lifecycle true
8 verbose lifecycle resumake.io@0.2.0~test:server: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;G:\resumake.io-master\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;G:\resumake.io-master\node_modules\.bin;C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services;C:\Python27\;C:\Python27\Scripts;C:\Program Files\PHP\v7.1;C:\Windows\system32\inetsrv;C:\Program Files\PHP\v7.3;C:\ProgramData\Boxstarter;C:\Program Files\Microsoft MPI\Bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files\Microsoft SQL Server\110\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\AOMEI Backupper;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files (x86)\Atmel\Flip 3.4.7\bin;C:\Users\omerf\AppData\Roaming\npm;C:\Program Files\JetBrains\PhpStorm 2019.1.3\bin;C:\Users\omerf\.dotnet\tools;C:\Program Files (x86)\Nmap;C:\Users\omerf\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\omerf\AppData\Local\Microsoft\WindowsApps
9 verbose lifecycle resumake.io@0.2.0~test:server: CWD: G:\resumake.io-master
10 silly lifecycle resumake.io@0.2.0~test:server: Args: [ '/d /s /c', 'cd app/server && npm test' ]
11 silly lifecycle resumake.io@0.2.0~test:server: Returned: code: 1  signal: null
12 info lifecycle resumake.io@0.2.0~test:server: Failed to exec test:server script
13 verbose stack Error: resumake.io@0.2.0 test:server: `cd app/server && npm test`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:203:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:203:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid resumake.io@0.2.0
15 verbose cwd G:\resumake.io-master
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:server"
18 verbose node v12.6.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error resumake.io@0.2.0 test:server: `cd app/server && npm test`
22 error Exit status 1
23 error Failed at the resumake.io@0.2.0 test:server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by saadq** [comment]
It would be easier to debug this over Slack, and then we can update here when fixed. Could you join the [Slack channel](https://github.com/saadq/resumake.io/issues/94) and then I can take a look later today or tomorrow.

**Comment by omerfraz** [comment]
Thanks for the invite. I headed over to Slack and checked the issue, its more likely the way we ran the scripts (client and server to run separately in two different command windows
i.e. **npm run start:client** and **npm run start:server**  in addition to some settings in webpack.dev.config.js i.e. 

    proxy: {
	'/api/**': {
	target: 'http://[::1]:3001',
	//secure: false,
	//changeOrigin: false,
	headers: {
            "Connection": "keep-alive"
        }
      }
    }

and a change in the client/package.json build was changed to production (was originally development) for making things moving.

"build": "cross-env NODE_ENV=**production** webpack --config webpack.prod.config.js --progress --profile --colors",

**Comment by saadq** [comment]
How did you install latex initially? Did you do it through MacTeX? (https://www.tug.org/mactex/)

I think MacTeX is the recommended solution for installing latex on Mac and usually comes with most of those packages installed.

**Comment by ars75** [comment]
Yes I installed MacTex first and then tried running the scripts. But now I’m running into Syntax errors for a few templates 😅 while others compile it just fine. Idk why that’s happening though. So will have to look into it next

**Comment by powertrio77** [comment]
I get Failed to load PDF file. I'm on windows10. I'm clicking the Make button to make a PDF. 

Where do I copy the folder node-latex-master? I pasted it here, C:\test\resumake.io-master\node-latex-master\
The only thing I ran was, "npm install node-latex"

Do I need to do anything else to install node-latex? Do I need to do something with the Usage code, mentioned in the readme.md? Thanks.

I have MikTex and TeXWorks installed. 
[HPM] Error occurred while trying to proxy request /api/generate/resume from localhost:3000 to http://localhost:3001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by jasonliu747** [comment]
Hi @saadq , I'm having the same issue on https://resumake.io
![image](https://user-images.githubusercontent.com/24452340/89270421-e5004180-d66d-11ea-89e5-f1dda3919bf0.png)
![image](https://user-images.githubusercontent.com/24452340/89270653-3d374380-d66e-11ea-9d37-e77e9b3aa839.png)
