### ISSUE TITLE
Issue with local copy

### ISSUE THREAD

**Issue by higheredd** [saadq/resumake.io#171]
Hi!

I cloned the project and ran it on my local machine. However, on clicking "Make" button, the error pops up.
![image](https://user-images.githubusercontent.com/87493885/126991092-18c9d633-30c3-41e5-8eb8-afb92aeffef4.png)

Console:
(The application runs on port 3000)

Error occurred while trying to proxy request /api/generate/resume from localhost:3000 to http://localhost:3001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by saadq** [comment]
How did you start the application? It seems like just the client is running and not the server.

**Comment by Bipinjot** [comment]
I followed these steps:

1. npm Install
2. Npm start

**Comment by saadq** [comment]
Which folder did you run that in? From your comment I'm guessing that you ran that inside just the `app/client` folder so only the client is running and not the server.

If you haven't already, please check out the [Setting Up](https://github.com/saadq/resumake.io/blob/main/contributing.md#setting-up) guide. But basically the simplest way to setup and run both the client and server:

1. Clone the repo
1. Run `npm run build` from the root directory
1. Run `npm start` from the root directory

**Comment by saadq** [comment]
Hey @Bipinjot and @higheredd can you let me know if you've tried the instructions I mentioned above?

**Comment by higheredd** [comment]
Hi @saadq 
I ran the commands in the root directory. The issue persists. I'm trying different things.

**Comment by firmprojects** [comment]
Facing exact same issue. I followed @saadq instruction above, but the error still persist.

**Comment by saadq** [comment]
Hey all, sorry to hear you guys are facing issues...

One other thing to try – Can you try to individually run the client and server?

1. Run `npm start` inside `app/client` in one terminal window
2. Run `npm start` inside `app/server` in one terminal window

**Comment by AlbyTree** [comment]
I have the same issue.
If I run the client and the server, I get this with Template1
```
  Error: LaTeX Syntax Error
  ! LaTeX Error: File `article.cls' not found.
  Enter file name:     \usepackage{amsmath}
  ! Undefined control sequence.
  \filename@simple ...t \relax \edef \filename@base
  !  ==> Fatal error occurred, no output PDF file produced!
      at ReadStream.<anonymous> (C:\Users\albyp\resumake\resumake.io\app\server\node_modules\node-latex\index.js:60:21)
      at ReadStream.emit (node:events:517:28)
      at ReadStream.emit (node:domain:489:12)
      at endReadableNT (node:internal/streams/readable:1368:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)
```
and this with the other templates (only the "I can't find file" parts change)
```
  Error: LaTeX Syntax Error
  ! I can't find file `'.
  ! I can't find file `'.
  ! I can't find file `\begin{document}'.
  ! I can't find file `\begin{document}'.
  ! I can't find file `\namesection{Your}{Name}{}'.
  ! I can't find file `\namesection{Your}{Name}{}'.
  ! I can't find file `\namesection{Your}{Name}{}'.
  ! I can't find file `\namesection{Your}{Name}{}'.
  ! I can't find file `\namesection{Your}{Name}{}'.
  ! I can't find file `\namesection{Your}{Name}{}'.
  ! I can't find file `\'.
  ! I can't find file `\end{document}'.
  ! Emergency stop.
      at ReadStream.<anonymous> (C:\Users\albyp\resumake\resumake.io\app\server\node_modules\node-latex\index.js:60:21)
      at ReadStream.emit (node:events:517:28)
      at ReadStream.emit (node:domain:489:12)
      at endReadableNT (node:internal/streams/readable:1368:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)
```
I'm on Windows 10, I installed NodeJs 18.18.0 (npm 9.8.1) and [TinyTeX ](https://yihui.org/tinytex/TinyTeX.zip) for Windows with the packages listed in the main branch guide.
I'm on the v2-(old) branch.

**Comment by Revo9919** [comment]
same issue
